version: '3.9'
services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"  # Maps PostgreSQL port to make it accessible
    volumes:
      # NOTE: to make this work with SELinux,
      # I need to add the :z at the end
      - lab-08-web-services:/var/lib/postgresql/data:z
      - ./src/init_data:/docker-entrypoint-initdb.d:z
  web:
    image: node:lts
    user: 'node'
    working_dir: /home/node/app
    env_file: .env
    environment:
      - NODE_ENV=development
    depends_on:
      - db
    ports:
      - "3000:3000"  # Maps application port to host
    volumes:
      - ./:/home/node/app  # Mounts the current directory to the container
    command: 'npm start'

# Persistent volume for database storage
volumes:
  lab-08-web-services:
